version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: member-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: memberdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  member-service:
    build: .
    container_name: member-service
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/memberdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
